baseURL = '/'
languageCode = 'en-us'
title = "Rohan's Blog"
theme = "cactus"
copyright = "Rohan Kapur"
enableGitInfo = true
enableRobotsTXT = true

[params]
colortheme = "dark"
description = "Hey, I'm Rohan. I'm currently a software developer at [Squads Protocol](https://squads.so/), The best ways to reach me are on Twitter and Telegram."
showProjectsList = true
rss = true
mathjax = true

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[params.social]]
  name = "github"
  link = "https://github.com/RohanKapurDEV"

[[params.social]]
  name = "twitter"
  link = "https://www.twitter.com/0xrohan"

[[params.social]]
  name = "email"
  link = "kapurrohan56@gmail.com" # no need for "mailto:" at the start